# Netlify Configuration for SpookySketch
[build]
  # Build command
  command = "cd frontend && npm install && npm run build"
  
  # Output directory (Next.js builds to .next)
  publish = "frontend/.next"
  
  # Base directory
  base = ""

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
